// Generated by CoffeeScript 1.10.0
(function() {
  this.app || (this.app = {});

  $(function() {
    var books;
    books = [
      {
        title: 'Javascript',
        author: 'Douglas',
        releaseDate: '2008',
        keywords: 'Programming'
      }, {
        title: 'The little book',
        author: 'Alex',
        releaseDate: '2012',
        keywords: 'Coffee'
      }, {
        title: 'Scala',
        author: 'Cay',
        releaseDate: '2013',
        keywords: 'Programm'
      }, {
        title: 'American',
        author: 'Bret',
        releaseDate: '1991',
        keywords: 'Novel'
      }, {
        title: 'Eloquent',
        author: 'Haver',
        releaseDate: '2011',
        keywords: 'Programming'
      }
    ];
    return new app.LibraryView(books);
  });

}).call(this);

//# sourceMappingURL=app.js.map
