// Generated by CoffeeScript 1.10.0
(function() {
  this.app || (this.app = {});

  app.Library = Backbone.Collection.extend({
    model: app.Book
  });

}).call(this);

//# sourceMappingURL=library.js.map
